### ISSUE TITLE
Error in log: inverter_ststus_fac

### ISSUE THREAD

**Issue by johanschelin** [weltmeyer/ha_sonnenbatterie#33]
Since upgrade to latest version be1b593 this error comes at every restart in the HA log:

inverter_status_fac' not in inverter/status/status/fac -> disabled

**Comment by weltmeyer** [comment]
Are you missing any sensor?
https://github.com/weltmeyer/ha_sonnenbatterie#unusedunavailable-sensors

**Comment by RustyDust** [comment]
@johanschelin 
> inverter_status_fac' not in inverter/status/status/fac -> disabled

This is **not** an error message as stated [here](https://github.com/weltmeyer/ha_sonnenbatterie#unusedunavailable-sensors). It just informs you that there is no entry for `fac` in the `inverter['status']['status']` array. This is quite normal since this variable seems to be only present in a small percentage of the installations. As you can see [here](https://github.com/weltmeyer/ha_sonnenbatterie/blob/be1b59347df786f9d816c1cab860d5523754e9de/custom_components/sonnenbatterie/mappings.py#L98-L117) the value is checked in two different places. For your installation it is found not found in the first location but is found in the second location `inverter['status']['fac]` and thus that value is used.

As you can see in the `aka` sections of both definitions, they also populate the `state_netfrequency` variable which is what you should use to display the net frequency in HA. I'm sorry but I couldn't come up with a better solution to "generalize" all the different possible locations for the actual grid frequency.

**Comment by johanschelin** [comment]
aaahh. Sorry I missed that. Setting this issue as closed.
