### ISSUE TITLE
Sonnenbatterie 10: tracking consumption + battery charging

### ISSUE THREAD

**Issue by pohly** [weltmeyer/ha_sonnenbatterie#37]
Thanks for the integration. I just got started with a new PV system with a Sonnenbatterie 10.

I have the ha_sonnenbatterie installed and it collects data - I'm just not sure what exactly I am getting :sweat_smile: 

Is "consumption w_total" the entire consumption of the house towards the grid? I'm currently feeding into the grid, so that number is negative.

What I haven't found is how much energy is consumed or provided by the battery itself. Is that perhaps "Current production (in)" and "Current production (out)"? Probably not.

Your screenshots show a "Sonnenbatterie" device (?). I suspect that might be a problem: I already had a "sonnenbatterie" device provided by the FritzBox integration, because that is also the name that I gave to the battery in my local network. Could it be that this now shadows whatever device ha_sonnenbatterie is adding?

**Comment by pohly** [comment]
I found "state_battery_inout" and several other "state_battery_*" sensors after looking at mapping.py - I think I have what I need :smile: 

Screenshots are nice, but a table with what sensors to expect from ha_battery would also help - just a suggestion.

**Comment by alsFC** [comment]
Hi!

**consumption w_total** is you current overall consumption, **production w_total** your current production, **Grid in/out power** would show negative values when your **Grid in/out power (in)** was higher than **Grid in/out power (out)**.

The integration unfortunately does not bundle the entities to a device in HA. That's why you don't get any sensors mapped to your existing device created by you network integration.

**Comment by RustyDust** [comment]
> Is "consumption w_total" the entire consumption of the house towards the grid?

Yes and no. It's the total consumption of the house and actually never should be negative. Whether the consumption is satisfied by the grid or the battery doesn't matter here.

> What I haven't found is how much energy is consumed or provided by the battery itself. Is that perhaps "Current production (in)" and "Current production (out)"? Probably not.

That should be "Battery in/out power". Negative numbers mean battery is loading, positive numbers mean battery is supplying power to consumers.

Current Production is the production of the PV system. "In" is always 0 for me (makes sense), "out" is what your PV currently produces.

> Your screenshots show a "Sonnenbatterie" device (?). I suspect that might be a problem: I already had a "sonnenbatterie" device provided by the FritzBox integration, because that is also the name that I gave to the battery in my local network. Could it be that this now shadows whatever device ha_sonnenbatterie is adding?

Unlikely, since the device identifiers are prefixed with the serial number of your Sonnenbatterie.

**Comment by pohly** [comment]
> > Is "consumption w_total" the entire consumption of the house towards the grid?
>
> It's the total consumption of the house and actually never should be negative.

Odd. It's definitely negative right now. The absolute value matches what the Sonnen app reports as energy flowing towards the grid.

**Comment by alsFC** [comment]
> Hi!
> 
> **consumption w_total** is you current overall consumption, **production w_total** your current production, **Grid in/out power** would show negative values when your **Grid in/out power (in)** was higher than **Grid in/out power (out)**.
> 
> The integration unfortunately does not bundle the entities to a device in HA. That's why you don't get any sensors mapped to your existing device created by you network integration.

with the latest release the entities are bundled to a device! Awesome!! :)

**Comment by weltmeyer** [comment]
Seems like no unresolved issue, or no new information. closing.
