### ISSUE TITLE
Unit side API disabled same time every night

### ISSUE THREAD

**Issue by Prythi** [weltmeyer/ha_sonnenbatterie#70]
Hi guys,

Just checking if other people have their sonnen battery go through some nightly diagnostics or maintenance that disables the API?

Mine seems to be u reachable for home assistant the same time every night. The battery itself still appears to work fine at that time and discharges appropriately without power interruption but my logs are showing that HAOS is unable to pull data from the API for a short period...

2024-12-26 03:40:45.062 ERROR (MainThread) [custom_components.sonnenbatterie]
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(...)
  OSError: [Errno 113] Host is unreachable

During handling of the above exception:
  urllib3.exceptions.NewConnectionError: Failed to establish a new connection: [Errno 113] Host is unreachable

During handling of the above exception:
  requests.exceptions.ConnectionError: HTTPConnectionPool(host='100.100.100.12', port=80): 
  Max retries exceeded with url: /api/battery

Traceback (most recent call last):
  File "/config/custom_components/sonnenbatterie/coordinator.py", line 83, in _async_update_data
    self.latestData["battery"] = await self.hass.async_add_executor_job(self.sbInst.get_battery)
  File "/usr/local/lib/python3.13/site-packages/sonnenbatterie/sonnenbatterie.py", line 130, in get_battery
    return self._get(SONNEN_API_PATH_BATTERY)
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 59, in request
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='100.100.100.12', port=80): 
Caused by NewConnectionError('<urllib3.connection.HTTPConnection object>: Failed to establish a new connection: [Errno 113] Host is unreachable')

OS
Home assistant operating system 14.1
Core 12.5
Supervisor 12.0

Integration
Latest as of December

Sonnen batterie
Eco 9.43

I've essentially been ignoring it for the past month and as far as I can tell there's no real problem other than the API going down at 3.40am every time so just checking if others have their sonnen batterie doing the same thing?

**Comment by rcruikshank** [comment]
Yes, same here.

**Comment by Prythi** [comment]
Ah OK.

Do you have an auto ignore set up for the logs or anything like that?

**Comment by rcruikshank** [comment]
No.  My HA system uses EMHASS to calculate changes to battery state every
30 seconds (and other loads like EV charging or pool pump etc.) and when it
calculates a change in charge or discharge or operation of some electrical
load in the house is required it updates a set of sensors in HA.  I then
use Node-Red to trigger an API call to the battery or switch on the Pool
Pump or charge the car according the the calculation.
If the API call to the battery fails I capture that and write it to a file
(I don't write it to the Node-Red logging system) and I just ignore that
file unless there is something more than one API call failing.

**Comment by Prythi** [comment]
Ahhh k. All good. Biggest thing was I wanted to see if others had the same
maint or api shut down nightly or if it was just my unit. I can sort it out
then and just figure out an ignore for that specific error.

Thanks!

**Comment by johanschelin** [comment]
I have the same, and it actually caused a problem for me as I use a switch template in config.yaml to create a switch for me for the Automatic/Manual mode. I have fixed it with a template in the switch that assumes the state is the same when unavailable - but it took some time for me to figure out that the api going unavailable was the root cause that my charging stopped (the unavailable state changed my switch "up and and down" which caused the nightly charging to be interrupted.

**Comment by johanschelin** [comment]
Would be nice if the integration could handle this and allow a timeout of perhaps 1-2min without changing the states.

**Comment by RustyDust** [comment]
@johanschelin 
> Would be nice if the integration could handle this and allow a timeout of perhaps 1-2min without changing the states.

See above ;) I (hopefully) made the integration play nice with an API that's unavailable for up to 3 minutes. My offline time window is coming up shorty so I'll see if it works out as planned.
Apart from that this PR should also report the "last known good" state instead of resetting the values to "unknown" or some other random value caused by the unresponsive API.

**Comment by johanschelin** [comment]
Manny thanks Stefan for the fix and for this great integration 👍

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: stefan ***@***.***>
Skickat: Friday, December 27, 2024 12:55:27 AM
Till: weltmeyer/ha_sonnenbatterie ***@***.***>
Kopia: Johan Schelin ***@***.***>; Mention ***@***.***>
Ämne: Re: [weltmeyer/ha_sonnenbatterie] Unit side API disabled same time every night (Issue #70)


@johanschelin<https://github.com/johanschelin>

Would be nice if the integration could handle this and allow a timeout of perhaps 1-2min without changing the states.

See above ;) I (hopefully) made the integration play nice with an API that's unavailable for up to 3 minutes. My offline time window is coming up shorty so I'll see if it works out as planned.
Apart from that this PR should also report the "last known good" state instead of resetting the values to "unknown" or some other random value caused by the unresponsive API.
